### ISSUE TITLE
Tests are no passing

### ISSUE THREAD

**Issue by rmariuzzo** [ogaston/utils-do#12]
I tried to add a change and found tests are not passing.

![image](https://user-images.githubusercontent.com/439839/94184063-5dff6680-fe71-11ea-9f34-e3a7f1dfaa86.png)

Consider to add CI for tests.

**Comment by Jadhielv** [comment]
@ogaston i think what is causing this test to fail is related to the logic of this function.

https://github.com/ogaston/utils-do/blob/3202da943be16db543b6e48330de9f9ec51ff39f/src/Validator/index.js#L105

**Comment by ogaston** [comment]
Thanks @Jadhielv 

it's been solved
